### PR TITLE
Changed a few DBI methods to dispatch over the first two arguments

### LINKED ISSUE #55: dbListFields() needs to dispatch over the first two arguments
for the upcoming version of DBI. This is a consequence of the definition of a default implementation for `dbListFields()` in DBI. I'm open to alternative suggestions, but it feels to me the easiest thing to do is to just change the dispatch and update documentation.

Reference: https://github.com/r-dbi/DBI/blob/master/revdep/problems.md#newly-broken-1

### PR DESCRIPTION
**Pull request by bborgesr**
(as per the default definition in [DBI](https://github.com/r-dbi/DBI/blob/master/R/DBConnection.R))

@krlmlr, thanks for letting me know about this issue. Are the changes here enough to close #55?
(To be on the safe side, I also went ahead and made the same change to other functions in this file that also have a default implementation in DBI with double dispatch.)

### CODE REVIEW

**Comment by krlmlr** [comment]
Thanks. To test this, can you please run `R CMD check` with the dev version of DBI? When do you plan to release to CRAN?

**Comment by bborgesr** [comment]
@krlmlr, I don't get any errors/warnings/messages on `devtools::check()` for pool, no matter which branch I'm in (master or dispatch), even if I'm on the dev version of DBI... So, it seems like you are catching something I can't replicate.

I released pool somewhat recently and I didn't have any plans for another release soon. But if this is a breaking change, I can do another release, np. When are you planning on releasing DBI?

**Comment by krlmlr** [comment]
Thanks for looking into it! DBI 0.8 is on CRAN, I mentioned that I contacted you regarding the check problems in *pool*.

**Comment by bborgesr** [comment]
Thanks @krlmlr, I also submitted pool 0.1.4 to CRAN yesterday and am now waiting for it to be accepted.

**Pull request merged**
