### PR TITLE
fix validate on SAP HANA

### LINKED ISSUE #103: Validation not working with SAP HANA
Hi, we just realized that the library fails queries using jdbc on a HANA database. The validation query "`SELECT COUNT (*) FROM SYSTABLES`" (`DBI-pool.R`, Line 46) fails in HANA because the table does not exist. It is rather "`SYS.TABLES`" or "`SYS_TABLES`" instead.

Minimal example:
```
pool_sap <- pool::dbPool(
  drv = RJDBC::JDBC(driverClass="com.sap.db.jdbc.Driver", classPath="/opt/jdbc/ngdbc.jar"),
  url = "jdbc:sap://db.url.de:30015/?autocommit=false",
  user = "user",
  password = "pwd"
)
result <- pool::dbGetQuery(pool_sap, "select * from table_smth;")
Error: Object does not appear to be valid. Error message: Validation not successful -- Unable to retrieve JDBC result set
  JDBC ERROR: SAP DBTech JDBC: [259] (at 21): invalid table name:  Could not find table/view SYSTABLES in schema user: line 1 col 22 (at pos 21)
  Statement: select count(*) from systables
In addition: Warning message:
It wasn't possible to activate and/or validate the object. Trying again with a new object. 
```

### PR DESCRIPTION
**Pull request by marcosci**
This merge fixes #103 and should fix the issues when working with SAP HANA.

### CODE REVIEW

**Comment by hadley** [comment]
I think we only need one of these. https://help.sap.com/docs/SAP_VORA/0991e2320f5940d988ed32b995d28a44/9a6dd95631c7446088984439c2439fad.html?version=1.4&locale=en-US says "Note that you can use "SYS." or "SYS_" to access system tables."

**Comment by federiva** [comment]
The `SYS_TABLES` option is not working in my case only the `SYS.TABLES` one

**Comment by hadley** [comment]
Ooops, that doc was for SAP VORA.

**Comment by hadley** [comment]
@federiva does `SELECT 1` also fail on SAP HANA?

**Comment by federiva** [comment]
@hadley Yup, I can confirm that `SELECT 1 from SYS.TABLES` is working as well (though returning many rows instead of only one) as the `count` function does.

**Comment by hadley** [comment]
@federiva I meant a bare `SELECT 1` with no table..

**Comment by federiva** [comment]
@hadley Nope, a bare `SELECT 1` without specifying the table is not working on my end (Getting a syntax error raised by JDBC)

**Comment by hadley** [comment]
@federiva thanks! 

@jcheng5 any concerns with adding additional checks here?

**Pull request merged**
